[package]
name = "sekret"
version = "0.1.1"
edition = "2021"
publish = false

[features]
ext_serde = ["serde"]

[dependencies]
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"
