# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    env:
      RUST_BACKTRACE: full
      RUST_LOG: debug

    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - --features ext_serde
          - --all-features

    steps:
      - uses: actions/checkout@v2

      - name: Restore Cargo cache
        uses: actions/cache@v2
        with:
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-${{ hashFiles('./Cargo.toml', './Cargo.lock') }}-${{ matrix.features }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ hashFiles('./Cargo.toml', './Cargo.lock') }}-
            cargo-${{ runner.os }}-

      - name: Test
        run: cargo test ${{ matrix.features }}
